<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>easynav_playground_summit</name>
  <version>0.5.0</version>
  <description>Easy Navigation playground with a Summit XL: EasyNav configurations and launchers for the Summit XL simulation (NavMap and Bonxai with RPP, MPPI and MPC; GPS fusion; warehouse logistics).</description>
  <maintainer email="fmrico@gmail.com">Francisco Martín Rico</maintainer>
  <license file="LICENSE">Apache-2.0</license>
  <author email="fmrico@gmail.com">Francisco Martín Rico</author>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <exec_depend>easynav_bonxai_maps_manager</exec_depend>
  <exec_depend>easynav_diagnostic_recovery</exec_depend>
  <exec_depend>easynav_fusion_localizer</exec_depend>
  <exec_depend>easynav_mpc_controller</exec_depend>
  <exec_depend>easynav_mppi_controller</exec_depend>
  <exec_depend>easynav_navmap_localizer</exec_depend>
  <exec_depend>easynav_navmap_maps_manager</exec_depend>
  <exec_depend>easynav_navmap_planner</exec_depend>
  <exec_depend>easynav_playground_summit_worlds</exec_depend>
  <exec_depend>easynav_regulated_pp_controller</exec_depend>
  <exec_depend>easynav_serest_controller</exec_depend>
  <exec_depend>easynav_simple_controller</exec_depend>
  <exec_depend>easynav_system</exec_depend>
  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  <exec_depend>launch_yaml</exec_depend>
  <exec_depend>navmap_rviz_plugin</exec_depend>
  <exec_depend>rviz2</exec_depend>
  <exec_depend>sensor_msgs</exec_depend>
  <exec_depend>tf2_ros</exec_depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
